### ISSUE TITLE
Progress message stucks at "Initializing..." when opening a single .js(or .ts) file with typescript-language-server.

### ISSUE THREAD

**Issue by BurningLutz** [WhoIsSethDaniel/lualine-lsp-progress.nvim#11]
When I open a single .js file (which is not belonging to a project) like `nvim index.js`，the progress message always stucks at "Initializing...".

![image](https://user-images.githubusercontent.com/15797639/222352551-ba1abbb7-3c90-46c9-9b0a-f61cb70ac79f.png)

After I viewed the `:LspLog`, I found that typescript-language-server never send `$/progress` notifications (which is not mandatory according to the [specification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initialize)) in such simple cases, and since the plugin updates progress messages only when `LspProgressUpdate` event is triggered, the progress message stucks forever.

**Comment by WhoIsSethDaniel** [comment]
Yes, I've filed #12 to fix this issue. Until that issue is resolved you should place this server in the `hide` configuration list. 

I should be able to deal with this over this coming weekend. Thanks for the report.

**Comment by WhoIsSethDaniel** [comment]
Hi, @BurningLutz . I believe this issue should be resolved. If you have placed tsserver in `hide` you should be able to remove it fro that and it should show 'initializing' followed by disappearing from the status line over the next few seconds (by default 3 seconds).

**Comment by BurningLutz** [comment]
It works now :D, thanks!
