### ISSUE TITLE
Stop working after recent changes in vim.lsp api

### ISSUE THREAD

**Issue by petobens** [WhoIsSethDaniel/lualine-lsp-progress.nvim#15]
Hi! The plugin stopped working after several progress/status changes in https://github.com/neovim/neovim/pull/23958

**Comment by WhoIsSethDaniel** [comment]
Thanks for letting me know. I don't always stay up-to-date with the latest nightly build so I had not seen this. The plugin should now work for stable and for nightly. Thanks again.

**Comment by petobens** [comment]
Awesome! Thank you :)
